// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3ekFgeJQEEmC58uuLfkDcf
// Component: tEVynI7_UD
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import MenuItem from "../../MenuItem"; // plasmic-import: f-aQjqzv9X/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_imbewu_mobile_first.module.css"; // plasmic-import: 3ekFgeJQEEmC58uuLfkDcf/projectcss
import sty from "./PlasmicSideNav.module.css"; // plasmic-import: tEVynI7_UD/css

export const PlasmicSideNav__VariantProps = new Array();

export const PlasmicSideNav__ArgProps = new Array();

function PlasmicSideNav__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"navHolder"}
        data-plasmic-override={overrides.navHolder}
        className={classNames(projectcss.all, sty.navHolder)}
      >
        <MenuItem
          className={classNames("__wab_instance", sty.menuItem__irhtW)}
        />

        <MenuItem
          className={classNames("__wab_instance", sty.menuItem__qhOi2)}
          txtMenu={"Menu txt"}
        />

        <MenuItem
          className={classNames("__wab_instance", sty.menuItem__t8Wt9)}
        />

        <MenuItem
          className={classNames("__wab_instance", sty.menuItem__ng8Ku)}
        />
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "navHolder"],
  navHolder: ["navHolder"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicSideNav__ArgProps,
      internalVariantPropNames: PlasmicSideNav__VariantProps
    });

    return PlasmicSideNav__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSideNav";
  } else {
    func.displayName = `PlasmicSideNav.${nodeName}`;
  }
  return func;
}

export const PlasmicSideNav = Object.assign(
  // Top-level PlasmicSideNav renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navHolder: makeNodeComponent("navHolder"),
    // Metadata about props expected for PlasmicSideNav
    internalVariantProps: PlasmicSideNav__VariantProps,
    internalArgProps: PlasmicSideNav__ArgProps
  }
);

export default PlasmicSideNav;
/* prettier-ignore-end */
