// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3ekFgeJQEEmC58uuLfkDcf
// Component: R9jI5HnTjk
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import NavPageTitle from "../../NavPageTitle"; // plasmic-import: _bfo_NMVKD/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_imbewu_mobile_first.module.css"; // plasmic-import: 3ekFgeJQEEmC58uuLfkDcf/projectcss
import sty from "./PlasmicHeaderBgSlice.module.css"; // plasmic-import: R9jI5HnTjk/css

export const PlasmicHeaderBgSlice__VariantProps = new Array();

export const PlasmicHeaderBgSlice__ArgProps = new Array();

function PlasmicHeaderBgSlice__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <NavPageTitle
        data-plasmic-name={"navPageTitle"}
        data-plasmic-override={overrides.navPageTitle}
        className={classNames("__wab_instance", sty.navPageTitle)}
      />
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "navPageTitle"],
  navPageTitle: ["navPageTitle"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHeaderBgSlice__ArgProps,
      internalVariantPropNames: PlasmicHeaderBgSlice__VariantProps
    });

    return PlasmicHeaderBgSlice__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHeaderBgSlice";
  } else {
    func.displayName = `PlasmicHeaderBgSlice.${nodeName}`;
  }
  return func;
}

export const PlasmicHeaderBgSlice = Object.assign(
  // Top-level PlasmicHeaderBgSlice renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navPageTitle: makeNodeComponent("navPageTitle"),
    // Metadata about props expected for PlasmicHeaderBgSlice
    internalVariantProps: PlasmicHeaderBgSlice__VariantProps,
    internalArgProps: PlasmicHeaderBgSlice__ArgProps
  }
);

export default PlasmicHeaderBgSlice;
/* prettier-ignore-end */
