// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3ekFgeJQEEmC58uuLfkDcf
// Component: fIbke3Hd6k
import * as React from "react";
import Head from "next/head";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import NavPageTitle from "../../NavPageTitle"; // plasmic-import: _bfo_NMVKD/component
import CardHomeSliderCarousel from "../../CardHomeSliderCarousel"; // plasmic-import: 4YXSdNetHE/component
import BtnNormal from "../../BtnNormal"; // plasmic-import: xohdOATSWS/component
import CardPricingSliderCarousel from "../../CardPricingSliderCarousel"; // plasmic-import: 6HXoSsrypS4/component
import WidgetAbout from "../../WidgetAbout"; // plasmic-import: fxukZgtzTS/component
import DotSliderItem from "../../DotSliderItem"; // plasmic-import: k9ppLUjiAw/component
import FooterWidget from "../../FooterWidget"; // plasmic-import: kn0Z3MZd2G/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_imbewu_mobile_first.module.css"; // plasmic-import: 3ekFgeJQEEmC58uuLfkDcf/projectcss
import sty from "./PlasmicImbewuHomeBase.module.css"; // plasmic-import: fIbke3Hd6k/css

export const PlasmicImbewuHomeBase__VariantProps = new Array();

export const PlasmicImbewuHomeBase__ArgProps = new Array();

function PlasmicImbewuHomeBase__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{"Homepage"}</title>
        <meta key="og:title" property="og:title" content={"Homepage"} />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__e80Kc)}>
            <NavPageTitle
              data-plasmic-name={"navPageTitle"}
              data-plasmic-override={overrides.navPageTitle}
              className={classNames("__wab_instance", sty.navPageTitle)}
              pageTitle={
                <div
                  data-plasmic-name={"pageTitle"}
                  data-plasmic-override={overrides.pageTitle}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.pageTitle
                  )}
                >
                  {"Welcome to Imbewu"}
                </div>
              }
            />

            <div
              data-plasmic-name={"outer"}
              data-plasmic-override={overrides.outer}
              className={classNames(projectcss.all, sty.outer)}
            >
              <CardHomeSliderCarousel
                data-plasmic-name={"cardHomeSliderCarousel"}
                data-plasmic-override={overrides.cardHomeSliderCarousel}
                className={classNames(
                  "__wab_instance",
                  sty.cardHomeSliderCarousel
                )}
              />

              <div className={classNames(projectcss.all, sty.freeBox__mSqx)}>
                <BtnNormal
                  data-plasmic-name={"btnHow"}
                  data-plasmic-override={overrides.btnHow}
                  className={classNames("__wab_instance", sty.btnHow)}
                  ghostGreen={true}
                >
                  {"how it works"}
                </BtnNormal>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__wqIvF)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pH4E
                )}
              >
                {"Our Plans"}
              </div>

              <CardPricingSliderCarousel
                data-plasmic-name={"cardPricingSliderCarousel"}
                data-plasmic-override={overrides.cardPricingSliderCarousel}
                className={classNames(
                  "__wab_instance",
                  sty.cardPricingSliderCarousel
                )}
              />

              <div className={classNames(projectcss.all, sty.freeBox__z9M8)}>
                <BtnNormal
                  data-plasmic-name={"btnSignup2"}
                  data-plasmic-override={overrides.btnSignup2}
                  className={classNames("__wab_instance", sty.btnSignup2)}
                >
                  {"SIGN UP NOW"}
                </BtnNormal>
              </div>
            </div>

            <WidgetAbout
              data-plasmic-name={"btnAbout"}
              data-plasmic-override={overrides.btnAbout}
              className={classNames("__wab_instance", sty.btnAbout)}
            />

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__v5Ed3)}
            >
              <img
                data-plasmic-name={"img"}
                data-plasmic-override={overrides.img}
                alt={""}
                className={classNames(projectcss.img, sty.img)}
                src={"/plasmic/imbewu_mobile_first/images/avatarjpg.jpeg"}
              />

              <div className={classNames(projectcss.all, sty.freeBox__wVCs)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rTmvs
                  )}
                >
                  {"Thuli Mokokeng"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cem6G
                  )}
                >
                  {"Imbewu Members Daughter "}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__uUspL
                  )}
                >
                  {
                    "I managed to pay my varsity bills with Mom’s Imbewu payout this year! We had fogotten about it. Such a nice surprise! "
                  }
                </div>
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__pm9Gr)}
            >
              <DotSliderItem
                className={classNames(
                  "__wab_instance",
                  sty.dotSliderItem__hBtiA
                )}
              />

              <DotSliderItem
                className={classNames(
                  "__wab_instance",
                  sty.dotSliderItem__gMb3Z
                )}
                currentSlide={true}
              />

              <DotSliderItem
                className={classNames(
                  "__wab_instance",
                  sty.dotSliderItem__vEcf
                )}
              />
            </p.Stack>

            <div className={classNames(projectcss.all, sty.freeBox__cNzUh)}>
              <BtnNormal
                data-plasmic-name={"btnSignup"}
                data-plasmic-override={overrides.btnSignup}
                className={classNames("__wab_instance", sty.btnSignup)}
              >
                {"SIGN UP NOW"}
              </BtnNormal>
            </div>

            <FooterWidget
              data-plasmic-name={"footerWidget"}
              data-plasmic-override={overrides.footerWidget}
              className={classNames("__wab_instance", sty.footerWidget)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "navPageTitle",
    "pageTitle",
    "outer",
    "cardHomeSliderCarousel",
    "btnHow",
    "cardPricingSliderCarousel",
    "btnSignup2",
    "btnAbout",
    "img",
    "btnSignup",
    "footerWidget"
  ],

  navPageTitle: ["navPageTitle", "pageTitle"],
  pageTitle: ["pageTitle"],
  outer: ["outer", "cardHomeSliderCarousel", "btnHow"],
  cardHomeSliderCarousel: ["cardHomeSliderCarousel"],
  btnHow: ["btnHow"],
  cardPricingSliderCarousel: ["cardPricingSliderCarousel"],
  btnSignup2: ["btnSignup2"],
  btnAbout: ["btnAbout"],
  img: ["img"],
  btnSignup: ["btnSignup"],
  footerWidget: ["footerWidget"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicImbewuHomeBase__ArgProps,
      internalVariantPropNames: PlasmicImbewuHomeBase__VariantProps
    });

    return PlasmicImbewuHomeBase__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicImbewuHomeBase";
  } else {
    func.displayName = `PlasmicImbewuHomeBase.${nodeName}`;
  }
  return func;
}

export const PlasmicImbewuHomeBase = Object.assign(
  // Top-level PlasmicImbewuHomeBase renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navPageTitle: makeNodeComponent("navPageTitle"),
    pageTitle: makeNodeComponent("pageTitle"),
    outer: makeNodeComponent("outer"),
    cardHomeSliderCarousel: makeNodeComponent("cardHomeSliderCarousel"),
    btnHow: makeNodeComponent("btnHow"),
    cardPricingSliderCarousel: makeNodeComponent("cardPricingSliderCarousel"),
    btnSignup2: makeNodeComponent("btnSignup2"),
    btnAbout: makeNodeComponent("btnAbout"),
    img: makeNodeComponent("img"),
    btnSignup: makeNodeComponent("btnSignup"),
    footerWidget: makeNodeComponent("footerWidget"),
    // Metadata about props expected for PlasmicImbewuHomeBase
    internalVariantProps: PlasmicImbewuHomeBase__VariantProps,
    internalArgProps: PlasmicImbewuHomeBase__ArgProps
  }
);

export default PlasmicImbewuHomeBase;
/* prettier-ignore-end */
