// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3ekFgeJQEEmC58uuLfkDcf
// Component: M2Fy1KeB8l
import * as React from "react";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_imbewu_mobile_first.module.css"; // plasmic-import: 3ekFgeJQEEmC58uuLfkDcf/projectcss
import sty from "./PlasmicBannerCarouselItemImgOnly.module.css"; // plasmic-import: M2Fy1KeB8l/css
import PlusRoundIcon from "./icons/PlasmicIcon__PlusRound"; // plasmic-import: oNedDfWT7/icon

export const PlasmicBannerCarouselItemImgOnly__VariantProps = new Array(
  "whitecard"
);

export const PlasmicBannerCarouselItemImgOnly__ArgProps = new Array();

function PlasmicBannerCarouselItemImgOnly__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_tokens,
        sty.root,
        {
          [sty.root__whitecard]: hasVariant(variants, "whitecard", "whitecard")
        }
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__kUyc2)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__gwF,
            {
              [sty.text__whitecard__gwF88Izt]: hasVariant(
                variants,
                "whitecard",
                "whitecard"
              )
            }
          )}
        >
          {"Headline here"}
        </div>
      </div>

      <div className={classNames(projectcss.all, sty.freeBox___0THAx)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text___1MhQp
          )}
        >
          {"Sub headline here"}
        </div>
      </div>

      <div
        className={classNames(projectcss.all, sty.freeBox__jgW, {
          [sty.freeBox__whitecard__jgW88Izt]: hasVariant(
            variants,
            "whitecard",
            "whitecard"
          )
        })}
      />

      <div className={classNames(projectcss.all, sty.freeBox__jphM3)}>
        <PlusRoundIcon
          data-plasmic-name={"svg"}
          data-plasmic-override={overrides.svg}
          className={classNames(projectcss.all, sty.svg)}
          role={"img"}
        />
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "svg"],
  svg: ["svg"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicBannerCarouselItemImgOnly__ArgProps,
      internalVariantPropNames: PlasmicBannerCarouselItemImgOnly__VariantProps
    });

    return PlasmicBannerCarouselItemImgOnly__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBannerCarouselItemImgOnly";
  } else {
    func.displayName = `PlasmicBannerCarouselItemImgOnly.${nodeName}`;
  }
  return func;
}

export const PlasmicBannerCarouselItemImgOnly = Object.assign(
  // Top-level PlasmicBannerCarouselItemImgOnly renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),
    // Metadata about props expected for PlasmicBannerCarouselItemImgOnly
    internalVariantProps: PlasmicBannerCarouselItemImgOnly__VariantProps,
    internalArgProps: PlasmicBannerCarouselItemImgOnly__ArgProps
  }
);

export default PlasmicBannerCarouselItemImgOnly;
/* prettier-ignore-end */
