// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3ekFgeJQEEmC58uuLfkDcf
// Component: rwgiY4v4Ww
import * as React from "react";
import Head from "next/head";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import BtnNormal from "../../BtnNormal"; // plasmic-import: xohdOATSWS/component
import BtnReadMore from "../../BtnReadMore"; // plasmic-import: nCdhjhK5Fp/component
import FooterWidget from "../../FooterWidget"; // plasmic-import: kn0Z3MZd2G/component
import { useScreenVariants as useScreenVariantstPLuZHt02V } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: tPLuZHt02v/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_imbewu_mobile_first.module.css"; // plasmic-import: 3ekFgeJQEEmC58uuLfkDcf/projectcss
import sty from "./PlasmicOtp.module.css"; // plasmic-import: rwgiY4v4Ww/css
import Icon11Icon from "./icons/PlasmicIcon__Icon11"; // plasmic-import: _14--lQom8/icon

export const PlasmicOtp__VariantProps = new Array();

export const PlasmicOtp__ArgProps = new Array();

function PlasmicOtp__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantstPLuZHt02V()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox___04F1Q)}>
            <div
              data-plasmic-name={"outer"}
              data-plasmic-override={overrides.outer}
              className={classNames(projectcss.all, sty.outer)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__deOD)}>
                <div className={classNames(projectcss.all, sty.freeBox__tz9Jw)}>
                  <div
                    data-plasmic-name={"text"}
                    data-plasmic-override={overrides.text}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text
                    )}
                  >
                    {"Please Enter Pin"}
                  </div>

                  <input
                    data-plasmic-name={"inputPin"}
                    data-plasmic-override={overrides.inputPin}
                    className={classNames(projectcss.input, sty.inputPin)}
                    placeholder={"One time pin"}
                    size={1}
                    type={"text"}
                    value={""}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__wFl9Q)}
                  >
                    <BtnNormal
                      data-plasmic-name={"submit"}
                      data-plasmic-override={overrides.submit}
                      className={classNames("__wab_instance", sty.submit)}
                    >
                      <button
                        data-plasmic-name={"submitBtn2"}
                        data-plasmic-override={overrides.submitBtn2}
                        className={classNames(
                          projectcss.button,
                          projectcss.__wab_text,
                          sty.submitBtn2
                        )}
                      >
                        {"SUBMIT"}
                      </button>
                    </BtnNormal>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox___3WJgh)}
                  >
                    <BtnNormal
                      data-plasmic-name={"btnResend"}
                      data-plasmic-override={overrides.btnResend}
                      className={classNames("__wab_instance", sty.btnResend)}
                      ghostGreen={true}
                    >
                      <button
                        data-plasmic-name={"submitBtn4"}
                        data-plasmic-override={overrides.submitBtn4}
                        className={classNames(
                          projectcss.button,
                          projectcss.__wab_text,
                          sty.submitBtn4
                        )}
                      >
                        {"RESEND PIN"}
                      </button>
                    </BtnNormal>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__pzFBf)}
                  >
                    <BtnReadMore
                      data-plasmic-name={"backBtn"}
                      data-plasmic-override={overrides.backBtn}
                      className={classNames("__wab_instance", sty.backBtn)}
                      slot={
                        <Icon11Icon
                          data-plasmic-name={"svg"}
                          data-plasmic-override={overrides.svg}
                          className={classNames(projectcss.all, sty.svg)}
                          role={"img"}
                        />
                      }
                    >
                      {"Go Back"}
                    </BtnReadMore>
                  </div>
                </div>
              </div>
            </div>

            <FooterWidget
              data-plasmic-name={"footerWidget"}
              data-plasmic-override={overrides.footerWidget}
              className={classNames("__wab_instance", sty.footerWidget)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "outer",
    "text",
    "inputPin",
    "submit",
    "submitBtn2",
    "btnResend",
    "submitBtn4",
    "backBtn",
    "svg",
    "footerWidget"
  ],

  outer: [
    "outer",
    "text",
    "inputPin",
    "submit",
    "submitBtn2",
    "btnResend",
    "submitBtn4",
    "backBtn",
    "svg"
  ],

  text: ["text"],
  inputPin: ["inputPin"],
  submit: ["submit", "submitBtn2"],
  submitBtn2: ["submitBtn2"],
  btnResend: ["btnResend", "submitBtn4"],
  submitBtn4: ["submitBtn4"],
  backBtn: ["backBtn", "svg"],
  svg: ["svg"],
  footerWidget: ["footerWidget"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicOtp__ArgProps,
      internalVariantPropNames: PlasmicOtp__VariantProps
    });

    return PlasmicOtp__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicOtp";
  } else {
    func.displayName = `PlasmicOtp.${nodeName}`;
  }
  return func;
}

export const PlasmicOtp = Object.assign(
  // Top-level PlasmicOtp renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    outer: makeNodeComponent("outer"),
    text: makeNodeComponent("text"),
    inputPin: makeNodeComponent("inputPin"),
    submit: makeNodeComponent("submit"),
    submitBtn2: makeNodeComponent("submitBtn2"),
    btnResend: makeNodeComponent("btnResend"),
    submitBtn4: makeNodeComponent("submitBtn4"),
    backBtn: makeNodeComponent("backBtn"),
    svg: makeNodeComponent("svg"),
    footerWidget: makeNodeComponent("footerWidget"),
    // Metadata about props expected for PlasmicOtp
    internalVariantProps: PlasmicOtp__VariantProps,
    internalArgProps: PlasmicOtp__ArgProps
  }
);

export default PlasmicOtp;
/* prettier-ignore-end */
