// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3ekFgeJQEEmC58uuLfkDcf
// Component: 4YXSdNetHE
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import CardHomeSlideItem from "../../CardHomeSlideItem"; // plasmic-import: r5_55WvnNsd/component
import IconRound from "../../IconRound"; // plasmic-import: fi0LamIfb0/component
import { useScreenVariants as useScreenVariantstPLuZHt02V } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: tPLuZHt02v/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_imbewu_mobile_first.module.css"; // plasmic-import: 3ekFgeJQEEmC58uuLfkDcf/projectcss
import sty from "./PlasmicCardHomeSliderCarousel.module.css"; // plasmic-import: 4YXSdNetHE/css
import ChartArcsvgIcon from "./icons/PlasmicIcon__ChartArcsvg"; // plasmic-import: 3SIKtHtH-5/icon
import CalendarMultipleChecksvgIcon from "./icons/PlasmicIcon__CalendarMultipleChecksvg"; // plasmic-import: s28DxDKdcY/icon

export const PlasmicCardHomeSliderCarousel__VariantProps = new Array();

export const PlasmicCardHomeSliderCarousel__ArgProps = new Array();

function PlasmicCardHomeSliderCarousel__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantstPLuZHt02V()
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"cardHolder"}
        data-plasmic-override={overrides.cardHolder}
        hasGap={true}
        className={classNames(projectcss.all, sty.cardHolder)}
      >
        <CardHomeSlideItem
          className={classNames("__wab_instance", sty.cardHomeSlideItem__ek6Hy)}
          slot2={
            "Protect those closest to you with a comprehensive family funeral benefit while receiving a guaranteed pay-out every year."
          }
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___6VCuY
            )}
          >
            {
              "Build toward financial lifestyle goals while protecting you & your legacy."
            }
          </div>

          <IconRound
            className={classNames("__wab_instance", sty.iconRound__riuSg)}
          />
        </CardHomeSlideItem>

        <CardHomeSlideItem
          className={classNames("__wab_instance", sty.cardHomeSlideItem__nayP)}
          slot={
            <img
              alt={""}
              className={classNames(projectcss.img, sty.img__z4HOr)}
              src={"/plasmic/imbewu_mobile_first/images/slideimg2Jpg.jpeg"}
            />
          }
          slot2={
            "Created in the spirit and values of abantu, it enables you to build toward financial and lifestyle goals while protecting you and your legacy. \n"
          }
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___3Q1Yw
            )}
          >
            {
              "Imbewu Stokvest™ is a unique digital stokvel product with added insurance benefits. "
            }
          </div>

          <IconRound
            className={classNames("__wab_instance", sty.iconRound__paSpv)}
            icon={
              <ChartArcsvgIcon
                className={classNames(projectcss.all, sty.svg__lGrtw)}
                role={"img"}
              />
            }
          />
        </CardHomeSlideItem>

        <CardHomeSlideItem
          className={classNames("__wab_instance", sty.cardHomeSlideItem__uLuc4)}
          slot={
            <img
              alt={""}
              className={classNames(projectcss.img, sty.img__oFeJ)}
              src={"/plasmic/imbewu_mobile_first/images/slideimg3Jpg.jpeg"}
            />
          }
          slot2={
            "And, there is no risk of not receiving your stokvel payout if other members don’t pay their contributions.\n"
          }
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__z7Wn
            )}
          >
            {"Only Imbewu Stokvest™ \npayouts are Guaranteed."}
          </div>

          <IconRound
            className={classNames("__wab_instance", sty.iconRound__i7Nos)}
            icon={
              <CalendarMultipleChecksvgIcon
                className={classNames(projectcss.all, sty.svg__qskqB)}
                role={"img"}
              />
            }
          />
        </CardHomeSlideItem>

        <CardHomeSlideItem
          className={classNames("__wab_instance", sty.cardHomeSlideItem__agi5B)}
          slot={
            <img
              alt={""}
              className={classNames(projectcss.img, sty.img__akcIs)}
              src={"/plasmic/imbewu_mobile_first/images/slicdeimg4Jpg.jpeg"}
            />
          }
          slot2={
            hasVariant(globalVariants, "screen", "mobile")
              ? "The app allows you to, manage your contributions, stokvel payouts, claims and much more all in the palm of your hand."
              : "The app allows you to, manage your contributions, stokvel payouts, claims and much more all in the palm of your hand."
          }
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__vM0Wf
            )}
          >
            {
              "Manage contributions, track payouts, and submit claims, all from the palm of your hand. "
            }
          </div>

          <IconRound
            className={classNames("__wab_instance", sty.iconRound___7TjDk)}
            icon={
              <CalendarMultipleChecksvgIcon
                className={classNames(projectcss.all, sty.svg___32Xx)}
                role={"img"}
              />
            }
          />
        </CardHomeSlideItem>
      </p.Stack>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "cardHolder"],
  cardHolder: ["cardHolder"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCardHomeSliderCarousel__ArgProps,
      internalVariantPropNames: PlasmicCardHomeSliderCarousel__VariantProps
    });

    return PlasmicCardHomeSliderCarousel__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCardHomeSliderCarousel";
  } else {
    func.displayName = `PlasmicCardHomeSliderCarousel.${nodeName}`;
  }
  return func;
}

export const PlasmicCardHomeSliderCarousel = Object.assign(
  // Top-level PlasmicCardHomeSliderCarousel renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    cardHolder: makeNodeComponent("cardHolder"),
    // Metadata about props expected for PlasmicCardHomeSliderCarousel
    internalVariantProps: PlasmicCardHomeSliderCarousel__VariantProps,
    internalArgProps: PlasmicCardHomeSliderCarousel__ArgProps
  }
);

export default PlasmicCardHomeSliderCarousel;
/* prettier-ignore-end */
