// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: p6tU1MHcNvqW8cSkqwHcz5
// Component: 2wY7mvgKVJ
import * as React from "react";
import Head from "next/head";
import Link from "next/link";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import TopMenu from "../../TopMenu"; // plasmic-import: dpTc1VI3P5/component
import { useScreenVariants as useScreenVariants_8UQYRsGwai } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 8U-qYRsGwai/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_panda.module.css"; // plasmic-import: p6tU1MHcNvqW8cSkqwHcz5/projectcss
import sty from "./PlasmicGetinvolved.module.css"; // plasmic-import: 2wY7mvgKVJ/css
import VerticalHRsvgIcon from "./icons/PlasmicIcon__VerticalHRsvg"; // plasmic-import: XmHlOAzX_A/icon
import Icon6Icon from "./icons/PlasmicIcon__Icon6"; // plasmic-import: L6LSWcuzGo/icon
import IconInstasvgIcon from "./icons/PlasmicIcon__IconInstasvg"; // plasmic-import: J9OPz5GQhT/icon
import IconTwsvgIcon from "./icons/PlasmicIcon__IconTwsvg"; // plasmic-import: xWz3mP7J7n/icon
import IconFbsvgIcon from "./icons/PlasmicIcon__IconFbsvg"; // plasmic-import: -3jNUbjHt8/icon

export const PlasmicGetinvolved__VariantProps = new Array();

export const PlasmicGetinvolved__ArgProps = new Array();

function PlasmicGetinvolved__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_8UQYRsGwai()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <TopMenu
            data-plasmic-name={"topMenu"}
            data-plasmic-override={overrides.topMenu}
            className={classNames("__wab_instance", sty.topMenu)}
          />

          <div className={classNames(projectcss.all, sty.freeBox__dztE)}>
            <div className={classNames(projectcss.all, sty.freeBox__l6Dcd)} />

            <div className={classNames(projectcss.all, sty.freeBox___0DqG)}>
              <div className={classNames(projectcss.all, sty.freeBox__muYQ)}>
                <VerticalHRsvgIcon
                  className={classNames(projectcss.all, sty.svg__t4Qs)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__dZ9W
                  )}
                >
                  {hasVariant(globalVariants, "screen", "desktopOnly")
                    ? "How you can get involved"
                    : "How you can get involved"}
                </div>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__lZs0L)} />

            {(
              hasVariant(globalVariants, "screen", "desktopOnly") ? true : true
            ) ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__ecCgZ)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__qdptj)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "desktopOnly")
                      ? "100%"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "desktopOnly")
                      ? "600px"
                      : "300px"
                  }
                  loading={
                    hasVariant(globalVariants, "screen", "desktopOnly")
                      ? "lazy"
                      : "lazy"
                  }
                  src={
                    hasVariant(globalVariants, "screen", "desktopOnly")
                      ? {
                          src: "/plasmic/panda/images/whatsAppImage20211210At1039241Jpeg.jpeg",
                          fullWidth: 1280,
                          fullHeight: 960,
                          aspectRatio: undefined
                        }
                      : {
                          src: "/plasmic/panda/images/whatsAppImage20211210At1039241Jpeg.jpeg",
                          fullWidth: 1280,
                          fullHeight: 960,
                          aspectRatio: undefined
                        }
                  }
                />

                {(
                  hasVariant(globalVariants, "screen", "desktopOnly")
                    ? true
                    : true
                ) ? (
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__udaMi)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "desktopOnly")
                        ? "100%"
                        : "100%"
                    }
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "desktopOnly")
                        ? "624px"
                        : "300px"
                    }
                    loading={
                      hasVariant(globalVariants, "screen", "desktopOnly")
                        ? "lazy"
                        : "lazy"
                    }
                    src={
                      hasVariant(globalVariants, "screen", "desktopOnly")
                        ? {
                            src: "/plasmic/panda/images/_61778005002244828Dc1Cb7Af9Cf8D81Jpeg.jpeg",
                            fullWidth: 1280,
                            fullHeight: 924,
                            aspectRatio: undefined
                          }
                        : {
                            src: "/plasmic/panda/images/whatsAppImage20211210At1039241Jpeg.jpeg",
                            fullWidth: 1280,
                            fullHeight: 960,
                            aspectRatio: undefined
                          }
                    }
                  />
                ) : null}
              </p.Stack>
            ) : null}
          </div>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox___0Igqy)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__hF633)}>
              <Icon6Icon
                className={classNames(projectcss.all, sty.svg__yWBve)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___54Yhq
                )}
              >
                {
                  "Donate any amount to our Non-Profit Organisation and become a member of our keep a girl child in school campaign."
                }
              </div>

              <button
                data-plasmic-name={"btnDonate"}
                data-plasmic-override={overrides.btnDonate}
                className={classNames(
                  projectcss.button,
                  projectcss.__wab_text,
                  sty.btnDonate
                )}
              >
                {hasVariant(globalVariants, "screen", "desktopOnly")
                  ? "Donate Now"
                  : "Donate Now"}
              </button>
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__x6BX8
              )}
            >
              {"Become an Ambassador"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__jmY1G
              )}
            >
              {
                "Become an Ambassador by using your connections and social media platforms to create awareness of Period Poverty and how it affects millions of women around the world. "
              }
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__bNtii)}
            >
              <button
                data-plasmic-name={"keepagirlinschool"}
                data-plasmic-override={overrides.keepagirlinschool}
                className={classNames(
                  projectcss.button,
                  projectcss.__wab_text,
                  sty.keepagirlinschool
                )}
                disabled={
                  hasVariant(globalVariants, "screen", "desktopOnly")
                    ? false
                    : false
                }
              >
                {hasVariant(globalVariants, "screen", "desktopOnly")
                  ? "#KeepAGirlInSchool"
                  : "#KeepAGirlInSchool"}
              </button>

              <button
                data-plasmic-name={"ecofriendly"}
                data-plasmic-override={overrides.ecofriendly}
                className={classNames(
                  projectcss.button,
                  projectcss.__wab_text,
                  sty.ecofriendly
                )}
              >
                {"#EcoFriendly"}
              </button>

              <button
                data-plasmic-name={"periodpoverty"}
                data-plasmic-override={overrides.periodpoverty}
                className={classNames(
                  projectcss.button,
                  projectcss.__wab_text,
                  sty.periodpoverty
                )}
              >
                {"#PeriodPoverty"}
              </button>
            </p.Stack>

            <div className={classNames(projectcss.all, sty.freeBox__fb4Cb)}>
              <IconInstasvgIcon
                data-plasmic-name={"instagram"}
                data-plasmic-override={overrides.instagram}
                className={classNames(projectcss.all, sty.instagram)}
                role={"img"}
              />

              <div className={classNames(projectcss.all, sty.freeBox__f7J23)}>
                <IconTwsvgIcon
                  data-plasmic-name={"twitter"}
                  data-plasmic-override={overrides.twitter}
                  className={classNames(projectcss.all, sty.twitter)}
                  role={"img"}
                />

                <div className={classNames(projectcss.all, sty.freeBox__ey7Kj)}>
                  <IconFbsvgIcon
                    data-plasmic-name={"facebook"}
                    data-plasmic-override={overrides.facebook}
                    className={classNames(projectcss.all, sty.facebook)}
                    role={"img"}
                  />
                </div>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__lq6Il)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___63Bvq
                )}
              >
                {"Set and forget "}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__gkzuc
                )}
              >
                {
                  "Set up a monthly debit order to make donating a hassle free contribution and ensuring there will always be someone new receiving a Care Kit every month "
                }
              </div>

              <button
                data-plasmic-name={"debitOrder"}
                data-plasmic-override={overrides.debitOrder}
                className={classNames(
                  projectcss.button,
                  projectcss.__wab_text,
                  sty.debitOrder
                )}
              >
                {hasVariant(globalVariants, "screen", "desktopOnly")
                  ? "Setup a monthly debit order"
                  : "Setup a monthly debit order"}
              </button>
            </div>
          </p.Stack>

          <div className={classNames(projectcss.all, sty.freeBox__w82Q1)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ujUj
              )}
            >
              {hasVariant(globalVariants, "screen", "desktopOnly") ? (
                <React.Fragment>
                  <React.Fragment>{""}</React.Fragment>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.a,
                      projectcss.__wab_text,
                      projectcss.plasmic_default__inline,
                      sty.link__yckgs
                    )}
                    component={Link}
                    href={"mailto:info@pandapads.co.za"}
                    platform={"nextjs"}
                  >
                    {"info@pandapads.co.za"}
                  </p.PlasmicLink>
                  <React.Fragment>
                    {
                      "\nSandi: 0834770123\nRebecca: 0795011862\nWe are based in Randburg, Johannesburg.\n"
                    }
                  </React.Fragment>
                </React.Fragment>
              ) : (
                <React.Fragment>
                  <React.Fragment>{""}</React.Fragment>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.a,
                      projectcss.__wab_text,
                      projectcss.plasmic_default__inline,
                      sty.link__vgF0Y
                    )}
                    component={Link}
                    href={"mailto:info@pandapads.co.za"}
                    platform={"nextjs"}
                  >
                    {"info@pandapads.co.za"}
                  </p.PlasmicLink>
                  <React.Fragment>
                    {
                      "\nSandi: 0834770123\nRebecca: 0795011862\nWe are based in Randburg, Johannesburg.\n"
                    }
                  </React.Fragment>
                </React.Fragment>
              )}
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "topMenu",
    "btnDonate",
    "keepagirlinschool",
    "ecofriendly",
    "periodpoverty",
    "instagram",
    "twitter",
    "facebook",
    "debitOrder"
  ],

  topMenu: ["topMenu"],
  btnDonate: ["btnDonate"],
  keepagirlinschool: ["keepagirlinschool"],
  ecofriendly: ["ecofriendly"],
  periodpoverty: ["periodpoverty"],
  instagram: ["instagram"],
  twitter: ["twitter"],
  facebook: ["facebook"],
  debitOrder: ["debitOrder"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicGetinvolved__ArgProps,
      internalVariantPropNames: PlasmicGetinvolved__VariantProps
    });

    return PlasmicGetinvolved__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicGetinvolved";
  } else {
    func.displayName = `PlasmicGetinvolved.${nodeName}`;
  }
  return func;
}

export const PlasmicGetinvolved = Object.assign(
  // Top-level PlasmicGetinvolved renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    topMenu: makeNodeComponent("topMenu"),
    btnDonate: makeNodeComponent("btnDonate"),
    keepagirlinschool: makeNodeComponent("keepagirlinschool"),
    ecofriendly: makeNodeComponent("ecofriendly"),
    periodpoverty: makeNodeComponent("periodpoverty"),
    instagram: makeNodeComponent("instagram"),
    twitter: makeNodeComponent("twitter"),
    facebook: makeNodeComponent("facebook"),
    debitOrder: makeNodeComponent("debitOrder"),
    // Metadata about props expected for PlasmicGetinvolved
    internalVariantProps: PlasmicGetinvolved__VariantProps,
    internalArgProps: PlasmicGetinvolved__ArgProps
  }
);

export default PlasmicGetinvolved;
/* prettier-ignore-end */
