// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import PaymentForm from "../components/PaymentForm";
import { PlasmicOurImpact } from "../components/plasmic/panda/PlasmicOurImpact";

function OurImpact() {
  const [showPayment, togglePayment] = React.useState(false);
  return <div><PlasmicOurImpact 
  
  btnDonate = {{
    onClick:(e)=>{
      togglePayment(!showPayment)
    }
  }}/>
  {showPayment && <div style={{width:'100%', height:"100%", position:'fixed', top:0, left:0}}>
    <PaymentForm
  btnClose = {{
    onClick:(e)=>{
      togglePayment(!showPayment)
    }
  }}
  />
  </div>}
  </div>;
}

export default OurImpact;
