// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PlasmicOurimpact } from "../components/plasmic/panda/PlasmicOurimpact";

function Ourimpact() {
 
  return <PlasmicOurimpact 
  
  facebook = {{
    onClick:(e)=>{
      window.open('https://www.facebook.com/PandaPads.SA/')
    }
  }}
  instagram = {{
    onClick:(e)=>{
      window.open('https://www.facebook.com/PandaPads.SA/')
    }
  }}
  />;
}

export default Ourimpact;
